apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: curso-hpa
  labels:
    app: curso-hpa
  namespace: provider-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cursos-server
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 80
          periodSeconds: 30
